User Page
WawrzenskiPatryk/montecinema pull request #9
Opened 2022-10-06 17:55 UTC by WawrzenskiPatryk

- User Page: user details & reservations 
- composables usage with script setup
- reservations grouping logic
- missing reservation removal logic
- bug fix: setting `DateInput` component's input type on update properly

2022-10-06 21:12 UTC, szymonlicau requested changes
Overall nice work, it seems like you are getting the hang of composition API, script setup and TS 😄

2022-10-06 21:12 UTC, szymonlicau commented on src/components/base/BaseTag.vue
> +}>();
I've seen you handling the "default" value by falling back to red if the prop is undefined - why not define a default this way 😄 ?
```suggestion
const props = withDefaults(defineProps<{
  theme?: 'gray' | 'red';
}>(), {
  theme: 'red'
});
```

2022-10-07 07:10 UTC, szymonlicau approved these changes

2022-10-07 07:10 UTC, WawrzenskiPatryk commented on src/components/base/BaseTag.vue
> +}>();
Got it!

Also I've removed imports of `defineProps` since it's a macro available globally 😅

2022-10-07 07:11 UTC, merged